taxi_co2:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../emissions.duckdb'
      database: 'emissions'
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
